language: c

compiler: gcc
    
install: true

stage: 
  - build
  - test

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      script: make -C all
    - stage: test
      script: echo test
