language: c

compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev
    
install: true

stage: 
  - build
  - test

branches:
  only:
    - master

jobs:
  include:
    - stage: build
      script: make -C shell-draft-1/ all -std=c99
    - stage: test
      script: echo testd
    - stage: test
      script: echo test
